spring:
   profiles:
     active: local
     group:
        local:
          - common
        test:
          - common

---
spring:
  config.activate.on-profile: common
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
scheduler:
  booking:
    delete-not-visited: "0 0 0 * * *"

---
spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  sql.init.mode: never
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

---
spring:
  config.activate.on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
