spring:
   profiles:
     active: local
     group:
        local:
          - common
        test:
          - common

---
spring:
  config.activate.on-profile: common
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql.init.mode: always
scheduler:
  booking:
    delete-not-visited: "0 0 0 * * *"

---
spring:
  config.activate.on-profile: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}

---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
