version: "2"
services:
  store-database:
    container_name: store-database
    build:
      dockerfile: Dockerfile
      context: ./mariadb
    image: store-mariadb
    environment:
      - MARIADB_DATABASE=reserve_store
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3308:3308"
    networks:
      - docker_store
  store-redis:
    container_name: store-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: store-redis
    ports:
      - "6379:6379"
    networks:
      - docker_store

networks:
  docker_store:
    driver: bridge
    external: true
